/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorBusqueda;
import Modelo.Status;
import javax.swing.JMenuItem;

/**
 * @author Estefania Baldini
 * @author Abel Márquez
 */
public class BusquedaProductos extends VentanaBase {




              String productos [] = null;
              String productoMuleta[] = null;
                int cantmax, posicionAct; 
                String productosCarrito = "";
    
    /**
     * Creates new form BusquedaProductos
     */
    public BusquedaProductos() {
        initComponents();
        Producto4.setVisible(false);
        Producto5.setVisible(false);
        Producto6.setVisible(false);
        Producto7.setVisible(false);
        Producto8.setVisible(false);
        Producto9.setVisible(false);
  
    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel10 = new javax.swing.JPanel();
        TituloRegistro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        IniciarSesionLbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        RegistrateLbl = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        LineaBusquedaTXT = new javax.swing.JTextField();
        BuscarLbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        AdminLbl = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Producto8 = new javax.swing.JPanel();
        TituloP7 = new javax.swing.JLabel();
        PrecioLbl7 = new javax.swing.JLabel();
        CntLbl7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Carro4 = new javax.swing.JLabel();
        PrecioP7 = new javax.swing.JLabel();
        CantidadP7 = new javax.swing.JLabel();
        Producto6 = new javax.swing.JPanel();
        TituloP6 = new javax.swing.JLabel();
        PrecioLbl4 = new javax.swing.JLabel();
        CntLbl5 = new javax.swing.JLabel();
        PrecioP6 = new javax.swing.JLabel();
        CantidadP6 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Carro3 = new javax.swing.JLabel();
        Producto7 = new javax.swing.JPanel();
        TituloP8 = new javax.swing.JLabel();
        PrecioLbl6 = new javax.swing.JLabel();
        CntLbl6 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Carro5 = new javax.swing.JLabel();
        PrecioP8 = new javax.swing.JLabel();
        CantidadP8 = new javax.swing.JLabel();
        Producto4 = new javax.swing.JPanel();
        TituloP4 = new javax.swing.JLabel();
        PrecioLbl5 = new javax.swing.JLabel();
        CntLbl4 = new javax.swing.JLabel();
        PrecioP4 = new javax.swing.JLabel();
        CantidadP4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Carro1 = new javax.swing.JLabel();
        Producto5 = new javax.swing.JPanel();
        TituloP5 = new javax.swing.JLabel();
        PrecioLbl3 = new javax.swing.JLabel();
        CntLbl3 = new javax.swing.JLabel();
        PrecioP5 = new javax.swing.JLabel();
        CantidadP5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Carro2 = new javax.swing.JLabel();
        SiguienteBtn = new javax.swing.JButton();
        CategoriaBox = new javax.swing.JComboBox();
        CategoriaLbl = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Producto9 = new javax.swing.JPanel();
        TituloP9 = new javax.swing.JLabel();
        PrecioLbl8 = new javax.swing.JLabel();
        CntLbl8 = new javax.swing.JLabel();
        PrecioP9 = new javax.swing.JLabel();
        CantidadP9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        carro6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloRegistro.setFont(new java.awt.Font("Times New Roman", 2, 48)); // NOI18N
        TituloRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.add(TituloRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 92, -1, -1));
        jPanel10.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1144, 11, -1, 189));
        jPanel10.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 176, -1, -1));
        jPanel10.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 151, -1, 48));

        IniciarSesionLbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        IniciarSesionLbl.setForeground(new java.awt.Color(255, 204, 51));
        IniciarSesionLbl.setText("Ingresa");
        IniciarSesionLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IniciarSesionLblMouseClicked(evt);
            }
        });
        jPanel10.add(IniciarSesionLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 204, 51));
        jLabel7.setText("/");
        jPanel10.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 50, -1, -1));

        RegistrateLbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RegistrateLbl.setForeground(new java.awt.Color(255, 204, 51));
        RegistrateLbl.setText("Inscribete");
        RegistrateLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrateLblMouseClicked(evt);
            }
        });
        jPanel10.add(RegistrateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 50, -1, -1));
        jPanel10.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 199, -1, -1));

        LineaBusquedaTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LineaBusquedaTXTActionPerformed(evt);
            }
        });
        jPanel10.add(LineaBusquedaTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 590, 31));

        BuscarLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/buscar.png"))); // NOI18N
        BuscarLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarLblMouseClicked(evt);
            }
        });
        jPanel10.add(BuscarLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 40, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/logoP.png"))); // NOI18N
        jPanel10.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 0, -1, -1));

        AdminLbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        AdminLbl.setForeground(new java.awt.Color(255, 204, 0));
        AdminLbl.setText("Vender");
        AdminLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminLblMouseClicked(evt);
            }
        });
        jPanel10.add(AdminLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 50, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 204, 51));
        jLabel11.setText("/");
        jPanel10.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 50, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/separador.png"))); // NOI18N
        jLabel20.setText("jLabel20");
        jPanel10.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1370, -1));

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1370, 90));

        jScrollPane1.setBackground(new java.awt.Color(255, 204, 0));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setForeground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel11.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1117, 265, -1, -1));

        Producto8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TituloP7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TituloP7.setText("jLabel10");

        PrecioLbl7.setText("Precio");

        CntLbl7.setText("Cantidad");

        jLabel10.setText("ImagArticulo");

        Carro4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/shopcart.png"))); // NOI18N
        Carro4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carro4MouseClicked(evt);
            }
        });

        PrecioP7.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        PrecioP7.setText("jLabel21");

        CantidadP7.setText("jLabel22");

        javax.swing.GroupLayout Producto8Layout = new javax.swing.GroupLayout(Producto8);
        Producto8.setLayout(Producto8Layout);
        Producto8Layout.setHorizontalGroup(
            Producto8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Producto8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Producto8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TituloP7)
                    .addGroup(Producto8Layout.createSequentialGroup()
                        .addGroup(Producto8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Producto8Layout.createSequentialGroup()
                                .addComponent(CntLbl7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CantidadP7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(22, 22, 22))
                            .addGroup(Producto8Layout.createSequentialGroup()
                                .addComponent(PrecioLbl7)
                                .addGap(18, 18, 18)
                                .addComponent(PrecioP7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(Carro4))
                    .addGroup(Producto8Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        Producto8Layout.setVerticalGroup(
            Producto8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Producto8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloP7)
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Producto8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Producto8Layout.createSequentialGroup()
                        .addGroup(Producto8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PrecioLbl7)
                            .addComponent(PrecioP7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Producto8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CntLbl7)
                            .addComponent(CantidadP7)))
                    .addComponent(Carro4))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel11.add(Producto8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, 200, 200));

        Producto6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TituloP6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TituloP6.setText("jLabel6");

        PrecioLbl4.setText("Precio");

        CntLbl5.setText("Cantidad");

        PrecioP6.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        PrecioP6.setText("jLabel11");

        CantidadP6.setText("jLabel12");

        jLabel18.setText("ImagArticulo");

        Carro3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/shopcart.png"))); // NOI18N
        Carro3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carro3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Producto6Layout = new javax.swing.GroupLayout(Producto6);
        Producto6.setLayout(Producto6Layout);
        Producto6Layout.setHorizontalGroup(
            Producto6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Producto6Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(Producto6Layout.createSequentialGroup()
                .addGroup(Producto6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Producto6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TituloP6))
                    .addGroup(Producto6Layout.createSequentialGroup()
                        .addGroup(Producto6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Producto6Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(PrecioLbl4))
                            .addGroup(Producto6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(CntLbl5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Producto6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PrecioP6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CantidadP6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Producto6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Producto6Layout.createSequentialGroup()
                    .addContainerGap(134, Short.MAX_VALUE)
                    .addComponent(Carro3)
                    .addGap(20, 20, 20)))
        );
        Producto6Layout.setVerticalGroup(
            Producto6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Producto6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloP6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Producto6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PrecioP6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PrecioLbl4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Producto6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CantidadP6)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Producto6Layout.createSequentialGroup()
                        .addComponent(CntLbl5)
                        .addContainerGap())))
            .addGroup(Producto6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Producto6Layout.createSequentialGroup()
                    .addContainerGap(146, Short.MAX_VALUE)
                    .addComponent(Carro3)
                    .addContainerGap()))
        );

        jPanel11.add(Producto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, -1, 199));

        Producto7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TituloP8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TituloP8.setText("jLabel8");

        PrecioLbl6.setText("Precio");

        CntLbl6.setText("Cantidad");

        jLabel19.setText("ImagArticulo");

        Carro5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/shopcart.png"))); // NOI18N
        Carro5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carro5MouseClicked(evt);
            }
        });

        PrecioP8.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        PrecioP8.setText("jLabel17");

        CantidadP8.setText("jLabel18");

        javax.swing.GroupLayout Producto7Layout = new javax.swing.GroupLayout(Producto7);
        Producto7.setLayout(Producto7Layout);
        Producto7Layout.setHorizontalGroup(
            Producto7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Producto7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Producto7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Producto7Layout.createSequentialGroup()
                        .addComponent(TituloP8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Producto7Layout.createSequentialGroup()
                        .addGroup(Producto7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Producto7Layout.createSequentialGroup()
                                .addComponent(CntLbl6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CantidadP8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 21, Short.MAX_VALUE))
                            .addGroup(Producto7Layout.createSequentialGroup()
                                .addComponent(PrecioLbl6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PrecioP8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Carro5)))
                .addContainerGap())
            .addGroup(Producto7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Producto7Layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(35, Short.MAX_VALUE)))
        );
        Producto7Layout.setVerticalGroup(
            Producto7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Producto7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloP8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addGroup(Producto7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Carro5)
                    .addGroup(Producto7Layout.createSequentialGroup()
                        .addGroup(Producto7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PrecioLbl6)
                            .addComponent(PrecioP8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Producto7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CntLbl6)
                            .addComponent(CantidadP8))))
                .addContainerGap())
            .addGroup(Producto7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Producto7Layout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(53, Short.MAX_VALUE)))
        );

        jPanel11.add(Producto7, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 410, -1, 200));

        Producto4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TituloP4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TituloP4.setText("jLabel3");

        PrecioLbl5.setText("Precio");

        CntLbl4.setText("Cantidad");

        PrecioP4.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        PrecioP4.setText("jLabel19");

        CantidadP4.setText("jLabel20");

        jLabel3.setText("ImagArticulo");

        Carro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/shopcart.png"))); // NOI18N
        Carro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carro1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Producto4Layout = new javax.swing.GroupLayout(Producto4);
        Producto4.setLayout(Producto4Layout);
        Producto4Layout.setHorizontalGroup(
            Producto4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Producto4Layout.createSequentialGroup()
                .addGroup(Producto4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Producto4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Producto4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Producto4Layout.createSequentialGroup()
                                .addComponent(CntLbl4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CantidadP4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TituloP4)
                            .addGroup(Producto4Layout.createSequentialGroup()
                                .addComponent(PrecioLbl5)
                                .addGap(18, 18, 18)
                                .addComponent(PrecioP4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(Carro1))
                    .addGroup(Producto4Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Producto4Layout.setVerticalGroup(
            Producto4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Producto4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloP4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Producto4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrecioLbl5)
                    .addComponent(PrecioP4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Producto4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Carro1)
                    .addGroup(Producto4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CntLbl4)
                        .addComponent(CantidadP4)))
                .addContainerGap())
        );

        jPanel11.add(Producto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 200, 199));

        Producto5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TituloP5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TituloP5.setText("jLabel3");

        PrecioLbl3.setText("Precio");

        CntLbl3.setText("Cantidad");

        PrecioP5.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        PrecioP5.setText("jLabel15");

        CantidadP5.setText("jLabel16");

        jLabel8.setText("ImagArticulo");

        Carro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/shopcart.png"))); // NOI18N
        Carro2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Carro2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Producto5Layout = new javax.swing.GroupLayout(Producto5);
        Producto5.setLayout(Producto5Layout);
        Producto5Layout.setHorizontalGroup(
            Producto5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Producto5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Producto5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Producto5Layout.createSequentialGroup()
                        .addGroup(Producto5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CntLbl3)
                            .addComponent(PrecioLbl3))
                        .addGap(16, 16, 16)
                        .addGroup(Producto5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CantidadP5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PrecioP5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(Carro2))
                    .addGroup(Producto5Layout.createSequentialGroup()
                        .addGroup(Producto5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Producto5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TituloP5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Producto5Layout.setVerticalGroup(
            Producto5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Producto5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Producto5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Producto5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Carro2))
                    .addGroup(Producto5Layout.createSequentialGroup()
                        .addComponent(TituloP5)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Producto5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PrecioP5)
                            .addComponent(PrecioLbl3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Producto5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CantidadP5)
                            .addComponent(CntLbl3))))
                .addContainerGap())
        );

        jPanel11.add(Producto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, -1, 199));

        SiguienteBtn.setBackground(new java.awt.Color(255, 153, 0));
        SiguienteBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SiguienteBtn.setText(">");
        SiguienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteBtnActionPerformed(evt);
            }
        });
        jPanel11.add(SiguienteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 470, -1, 35));

        CategoriaBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        CategoriaBox.setForeground(new java.awt.Color(102, 102, 102));
        CategoriaBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Accesorios Vehiculos", "Animales y Mascotas", "Bebes", "Camaras y Accesorios", "Celulares y Telefonos", "Coleccionables y Hobbies", "Computacion", "Consolas y Videojuegos", "Deportes y Fitness", "Electrodomesticos", "Electronica, Audio y Video", "Hogar y Muebles", "Industrias", "Instrumentos Musicales", "Juguetes", "Libros, Musica y Peliculas", "Relojes, Joyas y Bisuteria", "Ropa, Zapatos y Accesorios", "Salud y Belleza" }));
        jPanel11.add(CategoriaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 250, 31));

        CategoriaLbl.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        CategoriaLbl.setText("Categorias");
        jPanel11.add(CategoriaLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel12.setText("Lo más buscado:");
        jPanel11.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 186, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/imagenPrincipal.png"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel11.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 888, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel14.setText("¿Aún no tienes cuenta?");
        jPanel11.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 204, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("Inscríbete ya");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 350, 181, 48));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel15.setText("¡Encuentra lo que buscas!");
        jPanel11.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 550, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 204, 0));
        jLabel16.setText("Los mejores precios y productos publicados");
        jPanel11.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, -1, -1));

        Producto9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TituloP9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TituloP9.setText("jLabel9");

        PrecioLbl8.setText("Precio");

        CntLbl8.setText("Cantidad");

        PrecioP9.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        PrecioP9.setText("jLabel21");

        CantidadP9.setText("jLabel22");

        jLabel17.setText("ImagArticulo");

        carro6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/shopcart.png"))); // NOI18N
        carro6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carro6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Producto9Layout = new javax.swing.GroupLayout(Producto9);
        Producto9.setLayout(Producto9Layout);
        Producto9Layout.setHorizontalGroup(
            Producto9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Producto9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Producto9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Producto9Layout.createSequentialGroup()
                        .addComponent(TituloP9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Producto9Layout.createSequentialGroup()
                        .addGroup(Producto9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Producto9Layout.createSequentialGroup()
                                .addComponent(PrecioLbl8)
                                .addGap(18, 18, 18)
                                .addComponent(PrecioP9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(Producto9Layout.createSequentialGroup()
                                .addComponent(CntLbl8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CantidadP9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(carro6)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Producto9Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        Producto9Layout.setVerticalGroup(
            Producto9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Producto9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloP9)
                .addGap(18, 18, 18)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Producto9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Producto9Layout.createSequentialGroup()
                        .addGroup(Producto9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PrecioLbl8)
                            .addComponent(PrecioP9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Producto9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CntLbl8)
                            .addComponent(CantidadP9)))
                    .addGroup(Producto9Layout.createSequentialGroup()
                        .addComponent(carro6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel11.add(Producto9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 410, 200, -1));

        jScrollPane1.setViewportView(jPanel11);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1370, 700));

        jMenu3.setText("Comprador");

        jMenu6.setText("Ver Carrito de Compras");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenu3.add(jMenu6);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Inventario");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Administrador");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anadirElementosCoincidentes () {
        
        String productosCoincidentes = null;
      
        productosCoincidentes =  ControladorBusqueda.busquedaPorNombreyCategoria(LineaBusquedaTXT.getText(), CategoriaBox.getSelectedItem().toString());
        
          //ProductosCoincidentes contiene un String enorme con todos los productos en el TXT que cumplan con la categoria y el nombre
          // de la forma producto / producto / producto. Hay que hacerle SPLIT para poder usarlos
         System.out.println(productosCoincidentes);
         
         if (!productosCoincidentes.equals("")) {

        productos= productosCoincidentes.split("/");
        int cantidadProductosCoincidentes = productos.length;
        System.out.println(productos.length);
        System.out.println("Hay " + cantidadProductosCoincidentes + " productos validos.");
        
       for (int k = 0 ; k < 9 ; k++ ) {
        
           if (k <= cantidadProductosCoincidentes) {
               //    System.out.println(k);
                   productoMuleta = productos[k].split(";");
                   posicionAct ++;
               //    System.out.println("Arreglo de un producto con sus datos, posicion cero tiene -> " + productoMuleta[0]);
                   
               switch (k) {
                  
                   case 4: Producto4.setVisible(true);
                             TituloP4.setText(productoMuleta[0]);
                             PrecioP4.setText(productoMuleta[1]);
                             CantidadP4.setText(productoMuleta[4]);
                             break;
                   case 5: Producto5.setVisible(true);
                             TituloP5.setText(productoMuleta[0]);
                             PrecioP5.setText(productoMuleta[1]);
                             CantidadP5.setText(productoMuleta[4]);
                             break;
                   case 6: Producto6.setVisible(true);
                             TituloP6.setText(productoMuleta[0]);
                             PrecioP6.setText(productoMuleta[1]);
                             CantidadP6.setText(productoMuleta[4]);
                             break;
                   case 7: Producto7.setVisible(true);
                             TituloP8.setText(productoMuleta[0]);
                             PrecioP7.setText(productoMuleta[1]);
                             CantidadP7.setText(productoMuleta[4]);
                             break;
                   case 8: Producto8.setVisible(true);
                             TituloP7.setText(productoMuleta[0]);
                             PrecioP8.setText(productoMuleta[1]);
                             CantidadP8.setText(productoMuleta[4]);
                             break;
                   case 9: Producto9.setVisible(true);
                             TituloP9.setText(productoMuleta[0]);
                             PrecioP9.setText(productoMuleta[1]);
                             CantidadP9.setText(productoMuleta[4]);
                             break;
                 
                   
               }
               
           }
           
       }
         }
     //  System.out.println(posicionAct);
    }
    
    private void SiguienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteBtnActionPerformed
        
        //Debe cargar los siguientes elementos
        
       // System.out.println(posicionAct + " " + cantmax +" " + productos[11]);
        int ProductosCoincidentes = productos.length;
        
        if (ProductosCoincidentes > 9) {
               
                     Producto4.setVisible(false);
                     Producto5.setVisible(false);
                     Producto6.setVisible(false);
                     Producto7.setVisible(false);
                     Producto8.setVisible(false);

                                        for (int j = posicionAct ; j < ProductosCoincidentes ; j++ ) {

                                           if (j <= ProductosCoincidentes) {
                                               //    System.out.println(k);
                                                   productoMuleta = productos[j].split(";");
                                               //    System.out.println("Arreglo de un producto con sus datos, posicion cero tiene -> " + productoMuleta[0]);

                                               switch ((j-8)) {
                                                 
                                                   case 4: Producto4.setVisible(true);
                                                             TituloP4.setText(productoMuleta[0]);
                                                             PrecioP4.setText(productoMuleta[1]);
                                                             CantidadP4.setText(productoMuleta[4]);
                                                             break;
                                                   case 5: Producto5.setVisible(true);
                                                             TituloP5.setText(productoMuleta[0]);
                                                             PrecioP5.setText(productoMuleta[1]);
                                                             CantidadP5.setText(productoMuleta[4]);
                                                             break;
                                                   case 6: Producto6.setVisible(true);
                                                             TituloP6.setText(productoMuleta[0]);
                                                             PrecioP6.setText(productoMuleta[1]);
                                                             CantidadP6.setText(productoMuleta[4]);
                                                             break;
                                                   case 7: Producto7.setVisible(true);
                                                             TituloP8.setText(productoMuleta[0]);
                                                             PrecioP7.setText(productoMuleta[1]);
                                                             CantidadP7.setText(productoMuleta[4]);
                                                             break;
                                                   case 8: Producto8.setVisible(true);
                                                             TituloP7.setText(productoMuleta[0]);
                                                             PrecioP8.setText(productoMuleta[1]);
                                                             CantidadP8.setText(productoMuleta[4]);
                                                             break;
                                                  case 9: Producto9.setVisible(true);
                                                            TituloP9.setText(productoMuleta[0]);
                                                            PrecioP9.setText(productoMuleta[1]);
                                                            CantidadP9.setText(productoMuleta[4]);
                                                            break;

               }}}}
    }//GEN-LAST:event_SiguienteBtnActionPerformed

    private void AdminLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminLblMouseClicked

        VentanaInicioVendedor vendedor = new VentanaInicioVendedor();
        vendedor.setVisible(true);
        vendedor.setFatherWindow(this, true);

    }//GEN-LAST:event_AdminLblMouseClicked

    private void BuscarLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarLblMouseClicked

        if (!(CategoriaBox.getSelectedItem().toString().equals("") && LineaBusquedaTXT.getText().equals(""))) {
            anadirElementosCoincidentes();
        }

    }//GEN-LAST:event_BuscarLblMouseClicked

    private void LineaBusquedaTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LineaBusquedaTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LineaBusquedaTXTActionPerformed

    private void RegistrateLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrateLblMouseClicked

        VentanaRegistro registro = new VentanaRegistro();
        registro.setVisible(true);
        registro.setFatherWindow(this, true);

    }//GEN-LAST:event_RegistrateLblMouseClicked

    private void IniciarSesionLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarSesionLblMouseClicked

        VentanaInicioSesion iniciosesion = new VentanaInicioSesion();
        iniciosesion.setVisible(true);
        iniciosesion.setFatherWindow(this, true);

    }//GEN-LAST:event_IniciarSesionLblMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        VentanaRegistro registro = new VentanaRegistro();
        registro.setVisible(true);
        registro.setFatherWindow(this, true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Carro1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carro1MouseClicked
        
        productosCarrito = productosCarrito + TituloP4.getText() + ";" + "1" + ";"+ PrecioP4.getText() + ":" ;
        System.out.println("Producto añadido al carrito!");
    }//GEN-LAST:event_Carro1MouseClicked

    private void Carro2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carro2MouseClicked
        productosCarrito = productosCarrito + TituloP5.getText() + ";" + "1" + ";"+ PrecioP5.getText() + ":" ;
        System.out.println("Producto añadido al carrito!");
    }//GEN-LAST:event_Carro2MouseClicked

    private void Carro3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carro3MouseClicked
        productosCarrito = productosCarrito + TituloP6.getText() + ";" + "1" + ";"+ PrecioP6.getText() + ":" ;
            System.out.println("Producto añadido al carrito!");
    }//GEN-LAST:event_Carro3MouseClicked

    private void Carro4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carro4MouseClicked
        productosCarrito = productosCarrito + TituloP7.getText() + ";" + "1" + ";"+ PrecioP7.getText() + ":" ;
            System.out.println("Producto añadido al carrito!");
    }//GEN-LAST:event_Carro4MouseClicked

    private void Carro5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Carro5MouseClicked
      productosCarrito = productosCarrito + TituloP8.getText() + ";" + "1" + ";"+ PrecioP8.getText() + ":" ;
           System.out.println("Producto añadido al carrito!");
    }//GEN-LAST:event_Carro5MouseClicked

    private void carro6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carro6MouseClicked
       productosCarrito = productosCarrito + TituloP9.getText() + ";" + "1" + ";"+ PrecioP9.getText() + ":" ;
            System.out.println("Producto añadido al carrito!");
    }//GEN-LAST:event_carro6MouseClicked

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        System.out.println(productosCarrito);
        VentanaCarrito ventana = new VentanaCarrito(productosCarrito);
        ventana.setFatherWindow(this, true);
        ventana.setVisible(true);
        
    }//GEN-LAST:event_jMenu6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusquedaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusquedaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusquedaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusquedaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusquedaProductos().setVisible(true);
                
              
            
                      
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminLbl;
    private javax.swing.JLabel BuscarLbl;
    private javax.swing.JLabel CantidadP4;
    private javax.swing.JLabel CantidadP5;
    private javax.swing.JLabel CantidadP6;
    private javax.swing.JLabel CantidadP7;
    private javax.swing.JLabel CantidadP8;
    private javax.swing.JLabel CantidadP9;
    private javax.swing.JLabel Carro1;
    private javax.swing.JLabel Carro2;
    private javax.swing.JLabel Carro3;
    private javax.swing.JLabel Carro4;
    private javax.swing.JLabel Carro5;
    private javax.swing.JComboBox CategoriaBox;
    private javax.swing.JLabel CategoriaLbl;
    private javax.swing.JLabel CntLbl3;
    private javax.swing.JLabel CntLbl4;
    private javax.swing.JLabel CntLbl5;
    private javax.swing.JLabel CntLbl6;
    private javax.swing.JLabel CntLbl7;
    private javax.swing.JLabel CntLbl8;
    private javax.swing.JLabel IniciarSesionLbl;
    private javax.swing.JTextField LineaBusquedaTXT;
    private javax.swing.JLabel PrecioLbl3;
    private javax.swing.JLabel PrecioLbl4;
    private javax.swing.JLabel PrecioLbl5;
    private javax.swing.JLabel PrecioLbl6;
    private javax.swing.JLabel PrecioLbl7;
    private javax.swing.JLabel PrecioLbl8;
    private javax.swing.JLabel PrecioP4;
    private javax.swing.JLabel PrecioP5;
    private javax.swing.JLabel PrecioP6;
    private javax.swing.JLabel PrecioP7;
    private javax.swing.JLabel PrecioP8;
    private javax.swing.JLabel PrecioP9;
    private javax.swing.JPanel Producto4;
    private javax.swing.JPanel Producto5;
    private javax.swing.JPanel Producto6;
    private javax.swing.JPanel Producto7;
    private javax.swing.JPanel Producto8;
    private javax.swing.JPanel Producto9;
    private javax.swing.JLabel RegistrateLbl;
    private javax.swing.JButton SiguienteBtn;
    private javax.swing.JLabel TituloP4;
    private javax.swing.JLabel TituloP5;
    private javax.swing.JLabel TituloP6;
    private javax.swing.JLabel TituloP7;
    private javax.swing.JLabel TituloP8;
    private javax.swing.JLabel TituloP9;
    private javax.swing.JLabel TituloRegistro;
    private javax.swing.JLabel carro6;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    void setFatherWindow(AnadirCategoria aThis, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
