/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Usuario
 */
public class VentanaCarrito extends javax.swing.JFrame {

    /**
     * Creates new form VentanaCompras
     */
    public VentanaCarrito() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        TituloRegistro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        IniciarSesionLbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        RegistrateLbl = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        LineaBusquedaTXT = new javax.swing.JTextField();
        BuscarLbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloRegistro.setFont(new java.awt.Font("Times New Roman", 2, 48)); // NOI18N
        TituloRegistro.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.add(TituloRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 92, -1, -1));
        jPanel10.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1144, 11, -1, 189));
        jPanel10.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 176, -1, -1));
        jPanel10.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 151, -1, 48));

        IniciarSesionLbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        IniciarSesionLbl.setForeground(new java.awt.Color(255, 204, 51));
        IniciarSesionLbl.setText("Ingresa");
        IniciarSesionLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IniciarSesionLblMouseClicked(evt);
            }
        });
        jPanel10.add(IniciarSesionLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 60, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 204, 51));
        jLabel7.setText("/");
        jPanel10.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 60, -1, -1));

        RegistrateLbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RegistrateLbl.setForeground(new java.awt.Color(255, 204, 51));
        RegistrateLbl.setText("Inscribete");
        RegistrateLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrateLblMouseClicked(evt);
            }
        });
        jPanel10.add(RegistrateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 60, -1, -1));
        jPanel10.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 199, -1, -1));

        LineaBusquedaTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LineaBusquedaTXTActionPerformed(evt);
            }
        });
        jPanel10.add(LineaBusquedaTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 590, 31));

        BuscarLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/buscar.png"))); // NOI18N
        BuscarLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarLblMouseClicked(evt);
            }
        });
        jPanel10.add(BuscarLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 40, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/logoP.png"))); // NOI18N
        jPanel10.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 0, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/separador.png"))); // NOI18N
        jLabel20.setText("jLabel20");
        jPanel10.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1350, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 626, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IniciarSesionLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarSesionLblMouseClicked

        VentanaInicioSesion iniciosesion = new VentanaInicioSesion();
        iniciosesion.setVisible(true);
        iniciosesion.setFatherWindow(this, true);
    }//GEN-LAST:event_IniciarSesionLblMouseClicked

    private void RegistrateLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrateLblMouseClicked

        VentanaRegistro registro = new VentanaRegistro();
        registro.setVisible(true);
        registro.setFatherWindow(this, true);
    }//GEN-LAST:event_RegistrateLblMouseClicked

    private void LineaBusquedaTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LineaBusquedaTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LineaBusquedaTXTActionPerformed

    private void BuscarLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarLblMouseClicked

        if (!(CategoriaBox.getSelectedItem().toString().equals("") && LineaBusquedaTXT.getText().equals(""))) {
            anadirElementosCoincidentes();
        }
    }//GEN-LAST:event_BuscarLblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCarrito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BuscarLbl;
    private javax.swing.JLabel IniciarSesionLbl;
    private javax.swing.JTextField LineaBusquedaTXT;
    private javax.swing.JLabel RegistrateLbl;
    private javax.swing.JLabel TituloRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    // End of variables declaration//GEN-END:variables
}
